### ISSUE TITLE
ciphertext-plaintext multiplication and addition issue

### ISSUE THREAD

**Issue by ranran0523** [Desilo/liberate-fhe#21]
Hi, I am trying to use liberate.FHE to perform some HE operations between ciphertext and plaintext. However,  the API (cc_add & cc_mult) does not work with ciphertext and encoded messages. Are these functionalities not supported yet?

**Comment by juwhan-k** [comment]
@ranran0523 , cc_add and cc_mult is for cipher-cipher operations. You can simply use add and mult. Those functions detect the type of operands and calls proper routines. Also, when using add and mult, you don't have to worry about levels of the cipher texts. The levels are automatically matched as well.
